
import { Inter, Poppins } from "next/font/google";
import "../globals.css";
export const metadata = {
  title: 'Sign in',
  description: 'Generated by Next.js',
}

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${poppins.className} flex flex-col min-h-screen p-5 bg-background`}>{children}</body>
    </html>
  )
}
